os: linux
dist: focal
language: ruby
rvm: 2.7.3
env:
  global:
  - DATABASE_USERNAME=postgres
addons:
  postgresql: 13
cache:
  bundler: true
before_install:
- bundle config set without 'production'
- bundle config set deployment 'true'
- sudo apt-get -y install chromium-driver
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- bundle exec rake test_app
script:
- bundle exec rake spec
after_script:
- ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json
- ./cc-test-reporter upload-coverage -i coverage/codeclimate.json
after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
