name: Ruby

on:
  - push
  - pull_request

env:
  CI: "true"
  NODE_VERSION: 16.9.1

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2-alpine
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: |
        gem install bundler -v 2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build and test
      run: |
        bundle exec rake test_app > /dev/null 2>&1 || true
        wget https://raw.githubusercontent.com/decidim/decidim/23662d3f511a442c15519c541647c384f9ab5159/decidim-generators/lib/decidim/generators/app_templates/webpacker.yml -O spec/decidim_dummy_app/config/webpacker.yml
        cd spec/decidim_dummy_app
        bundle exec rails webpacker:binstubs
        bundle exec rails decidim:webpacker:install
        bundle exec rails decidim:choose_target_plugins
        bundle exec rails railties:install:migrations
        bundle exec rails db:create
        bundle exec rails db:environment:set
        bundle exec rails db:migrate
        bundle exec rails db:test:prepare
        RAILS_ENV=test bundle exec rails webpacker:compile
        cd ../..
        bundle exec rspec
