name: Ruby

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: |
        gem install bundler -v 2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build and test
      env:
        RAILS_ENV: test
        DATABASE_HOST: postgres
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres
      run: |
        bundle exec rake test_app || true
        wget https://raw.githubusercontent.com/decidim/decidim/23662d3f511a442c15519c541647c384f9ab5159/decidim-generators/lib/decidim/generators/app_templates/webpacker.yml -O spec/decidim_dummy_app/config/webpacker.yml
        cd spec/decidim_dummy_app
        bundle exec rails webpacker:binstubs
        bundle exec rails decidim:webpacker:install
        cd ../..
        bundle exec rspec
