name: Ruby

on:
  - push

env:
  CI: "true"
  NODE_VERSION: 16.9.1
  DECIDIM_MODULE: decidim-calendar

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2-alpine
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm get cache)-${{ env.DECIDIM_MODULE }}"
    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir-path.outputs.dir }}
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-
    - name: Build and test
      run: |
        npm install
        Y | bundle exec rake test_app > /dev/null
        cd spec/decidim_dummy_app
        gem install decidim -v=0.25.2
        yarn add @rails/webpacker@^6.0.0-rc.6
        RAILS_ENV=test bundle exec rails webpacker:compile
        cd ../..
        bundle exec rake spec
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 6e1f20efc5825ad174752f381d2cda8f2ba021589a23df1ddb91d86f803c5d31
      with:
        coverageLocations: ${{github.workspace}}/coverage/coverage.xml:cobertura
